name: Go-build-macos

on:
  push:
    branches:
      - main  # Change this to the branch you want to build on push

jobs:
  build-macos:
    name: build-macos
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [amd64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64


    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v -o agdownloader-${{ matrix.os }}-${{ matrix.goarch }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./agdownloader-${{ matrix.os }}-${{ matrix.goarch }}
          asset_name: agdownloader-${{ matrix.os }}-${{ matrix.goarch }}
          asset_content_type: application/octet-stream

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: agdownloader
          path: |
            agdownloader_*
