# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-build-macos

on:
  push:
    branches:
      - main  # Change this to the branch you want to build on push

jobs:
  build-macos:
    name: build-macos
    
    strategy:
      matrix:
        # macos-12: amd64 (oldest supported version as of 05-02-2024)
        # macos-14: arm64 (oldest arm64 version)
        os: [macos-12, macos-14]
        include:
          - os: macos-12
            goarch: amd64
          - os: macos-14
            goarch: arm64
        go-version: [ '1.20', '1.22.4' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version

      - name: Build
        run: go build -v main.go

    
